---
title: "Programming Principles I with JavaScript"
subtitle: "Course Outline"
author: "Brad Cupp"
date: "Fall 2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Week One
#### Monday, 8/26
* Syllabus highlights (20 min.)
* Definitons of language and grammar (20 min.)
    + [Languages and Grammar (pdf)](https://www.cslab.pepperdine.edu/cupp/textbook/cfqtCh02.pdf)
    + slides
* Grammar A--Identifiers (10 min.)
    + Is $b$ a valid identifier by grammar A? If so, show the syntax tree. $\color{red}{15}$
    + Is $d$ a valid identifier by grammar A? If so, show the syntax tree. $\color{red}{\text{invalid}}$
    + Is $abc$ a valid identifier by grammar A? If so, show the syntax tree. $\color{red}{221456}$
    + Is $cb3$ a valid identifier by grammar A? If so, show the syntax tree. $\color{red}{321659}$
    + Is $2b$ a valid identifier by grammar A? If so, show the syntax tree. $\color{red}{\text{invalid}}$
    + Is $ab12c$ a valid identifier by grammar A? If so, show the syntax tree. $\color{red}{2332145786}$

#### Tuesday, 8/27
* Grammar A review (5 min.)
* Grammar B--Signed Integers (10 min.)
    + Definition of leftmost derivation
    
        > A *leftmost derivation* of a string is a derivation
        > in which symbols to the left in the syntax tree
        > are expanded before symbols to the right in the 
        > syntax tree, and the rule number invoked for each
        > expansion is recorded.
    
    + Is $+d$ a valid identifier by grammar B? If so, give the leftmost derivation. $\color{red}{126}$
    + Is $-dddd$ a valid identifier by grammar B? If so, give the leftmost derivation. $\color{red}{135556}$
    + Is $ddd$ a valid identifier by grammar B? If so, give the leftmost derivation. $\color{red}{14556}$
    + Give an example of a string that is invalid by grammar B. $\color{red}{b, ddd+, d+d, etc.}$
* Grammar C--Context-Sensitive Grammar (15 min.)
    + Is $abc$ a valid string by Grammar C? If so, give the leftmost derivation. $\color{red}{25}$
    + Is $aabbcc$ a valid string by Grammar C? If so, give the leftmost derivation. $\color{red}{123456}$
    + Is $aaabbbccc$ a valid string by Grammar C? If so, give the leftmost derivation. $\color{red}{11233344566}$
    + What language does grammar C recognize? $\color{red}{\text{strings of the form } a^nb^nc^n\text{ for }n > 0}$
* Grammar D--Expressions (20 min.)
    + Is $a$ a valid expression by Grammar D? If so, give the leftmost derivation. $\color{red}{246}$
    + Is $a + a$ a valid expression by Grammar D? If so, give the leftmost derivation. $\color{red}{124646}$
    + Is $a * a$ a valid expression by Grammar D? If so, give the leftmost derivation. $\color{red}{23466}$
    + Is $a + a * a$ a valid expression by Grammar D? If so, give the leftmost derivation. $\color{red}{12463466}$
    + Is $(a * a)$ a valid expression by Grammar D? If so, give the leftmost derivation. $\color{red}{24523466}$
    + Is $a * (a * a + a) + a$ a valid expression by Grammar D? If so, give the leftmost derivation. $\color{red}{1234651234664646}$
    
#### Thursday, 8/29
* Questions from homework, J1 due tonight
    + Quiz on syntax trees
* Brief introduction to VS Code, emphasis on console
* JavaScript literals

    > A *literal* is an atomic value that can be used in a JavaScript expression
    
    + Attributes of a literal (at any point in time a literal has a ...)
        1. type
        2. value
    + Types
        + number (i.e. 4, -32, 3.14159)
            - typeof operator (unary prefix)
            - `typeof 8`
        + string (i.e. 'bird', 'c', 'Pepperdine University')
        + boolean (i.e. true, false)
        + function (Math.sqrt, console.log, **Note: these are not literals. We'll learn about function literals later **)
* JavaScript variables
    + Attributes of a variable (at any point in time a variable has a ...)
        1. name
        2. type
        3. value
    + Variables in math (free to take any value) vs. variables in programming (bound to a single value)
    + Assignment
        - `let x = 4;`
        - Read as "let x get 4"
        - `let` only used on first occurrence of variable
        - Subsequent usage: `x = 3` ("x gets 3") changes value of `x`
        - Lefthand side of assignment must be a single variable
        - Righthand side can be any expression
        - Type of variable is inferred from expression
            - can change in standard JavaScript
            - cannot change in TypeScript
    + Constants
        - `const TAX_RATE = 0.095;`
        - Same as `let` but TAX_RATE cannot be changed
        - All caps is standard convention for names of constants
        - `var x = 4;` is for backwards compatibility, do not use
* Arithmetic Operators (in order of precedence)
    + unary plus `+`, unary negation `-`
    + multiplication `*`, division `\`, modulus `%`
    + addition `+`, subtraction `-`
        - Note: no exponentiation operator, use `Math.pow(x, 2)`
        - Note: no integer division operator, use `Math.floor(x / 2)`, see next lecture
* First programs

<hr/>
###### hello.ts
Write a program that prints the string `Hello, world!` to the console.
```{js}
console.log("Hello, world!\n");
```

<hr/>
###### rectangle.ts  
Write a program that computes and prints the area and perimeter of a rectangle
with variable length and width to the console.
```{js}
  let length = 4.2;
  let width = 5.8;
  let area = length * width;
  let perimeter = 2.0 * (length + width);
  console.log("Area = " + area.toFixed(1));
  console.log("Perimeter = " + perimeter.toFixed(1));
```

### Week Two
#### Monday, 9/2
* Labor Day (no class)

#### Tuesday, 9/3
* User-defined functions
    + Function syntax
    + Function literals
* Sample code

<hr/>
###### triple.ts  
```{js}
function double(x: number): number {
  return 2 * x;
}

const triple = function(x: number): number {
  return 3 * x;
}

const magnify = function(x: number, factor: number = 2): number {
  return x
}

console.log("double(6) -> " + double(6));
console.log("triple(8) -> " + triple(8));
console.log("magnify(9) -> " + magnify(9));
console.log("magnify(6, 4) -> " + magnify(6, 4));
console.log("double(7, 5) -> " + magnify(7, 5));
```

<hr/>
###### rectangleFunctions.ts  
```{js}
function area(length: number, width: number): number {
  return length * width;
}

function perimeter(length: number, width: number): number {
  return 2.0 * (length + width);
}

function describeRectangle(length: number, width: number): void {
  console.log("length: " + length.toFixed(1));
  console.log("width: " + width.toFixed(1));
  console.log("area: " + area(length, width).toFixed(2));
  console.log("perimeter: " + perimeter(length, width).toFixed(2));
  console.log();
}

describeRectangle(3.0, 4.0);
describeRectangle(8.6, 5.1);
describeRectangle(13.2, 2.5);
```

#### Thursday, 9/5
* Questions from homework, J2 due tonight
    + `meters(feet: number, inches: number): number`
    + `celsius(fahrenheit: number): number`
* Integer arithmetic
    + integer division `Math.floor(32 / 5)`
    + modulus operator `32 % 5`
* Array literals
    + A collection of values into a single container
    + `[4, 8, 2]`
    + Can be assigned to a variable
    + Can be used to return multiple values from a function
    + Individual elements retrieved by index, i.e. `x[0]`, `x[1]`, etc.
    + We'll learn more about arrays later

<hr/>
###### hyp.ts

```{js}
function hypotenuse(sideA: number, sideB: number): number {
    let sum = Math.pow(sideA, 2) + Math.pow(sideB, 2);
    return Math.sqrt(sum);
    
    // return Math.sqrt(Math.pow(sideA, 2) + Math.pow(sideB, 2));
  }
  
  console.log();
  console.log("hypotenuse(3, 4) => " + hypotenuse(3, 4).toFixed(1));
  console.log("hypotenuse(12, 8) => " + hypotenuse(12, 8).toFixed(2));
  console.log("hypotenuse(9, 16) => " + hypotenuse(9, 16).toFixed(2));
  console.log();
```

<hr/>
###### change.ts

```{js}
function change(cents: number): number[] {
  let quarters = Math.floor(cents / 25);
  cents = cents % 25;
  let dimes = Math.floor(cents / 10);
  cents = cents % 10;
  let nickels = Math.floor(cents / 5);
  cents = cents % 5;
  return [quarters, dimes, nickels, cents];
}

function reportChange(cents: number): void {
    let coins = change(cents);
    console.log();
    console.log("Change for " + cents + " cents: ");
    console.log("\tQuarters: " + coins[0]);
    console.log("\tDimes: " + coins[1]);
    console.log("\tNickels: " + coins[2]);
    console.log("\tPennies: " + coins[3]);
    console.log();
}

reportChange(89);
reportChange(37);
reportChange(5);
reportChange(68);
reportChange(99);
```

### Week Three
#### Monday, 9/9
* Questions from the homework, J3 due tonight
  + `operations(x: number, y: number): number[]`
  + `weeksDaysHours(hours: number): number[]`

#### Tuesday, 9/10

#### Thursday, 9/12
* Questions from the homework, J4 due tonight
  + `commission(sales: number): number`
  + `prize(score1: number, score2: number, score3: number): number`

### Week Four
#### Monday, 9/16
* Questions from the homework, J5 due tonight
  + `fine(speed: number): number`
  + `deansList(numA: number, numB: number, numC: number, numD: number, numF: number): string`

#### Tuesday, 9/17

#### Thursday, 9/19
* Questions from the homework, J6 due tonight
  + Read [Nested Selections, Assertions and Invariants (pp. 36-43)](https://www.cslab.pepperdine.edu/cupp/textbook/cfqtCh08.pdf)
  + strongest invariant problems
  + `discOrder(quantity: number): number`

### Week Five
#### Monday, 9/23
* Questions from the homework, J7 due tonight
  + additional strongest invariant problems
  + `inorder(a: number, b: number, c: number): number[]`

#### Tuesday, 9/24

#### Thursday, 9/26
* Questions from the homework, J8 due tonight
  + `stripTitle(name: string): string`
  + `lastNameFirst(name: string): string`
  + `pigLating(word: string): string`
  
### Week Six
#### Monday, 9/30
* EXAM ONE

#### Tuesday, 10/1

#### Thursday, 10/3
* No assignment due

### Week Seven
#### Monday, 10/7
* Questions from the homework, J9 due tonight
  + FSM construction problems

#### Tuesday, 10/8

#### Thursday, 10/10
* Questions from the homework, J10 due tonight
  + Regular Expressino to FSM conversion problems
  
### Week Eight
#### Monday, 10/14
* Questions from the homework, J11 due tonight
  + Written loop problems
  + `ddb(cost: number, n: number, k: number): number`
  + `euler(k: number): number`

#### Tuesday, 10/15

#### Thursday, 10/17
* Questions from the homework, J12 due tonight
  + `dec2bin(dec: number): string`
  + `bin2dec(bin: string): number`
  + `dec2hex(dec: number): string`
  
### Week Nine
#### Monday, 10/21
* Questions from the homework, J13 due tonight
  + Written loop problems
  + `ddb(cost: number, n: number, k: number): number`
  + `euler(k: number): number`

#### Tuesday, 10/22

#### Thursday, 10/24
* Questions from the homework, J14 due tonight
  + `fib(n: number): number[]`
  + `evenSum(v: number[]): number`
  + `negCount(v: number[]): number`
  
### Week Ten
#### Monday, 10/28
* Questions from the homework, J15 due tonight
  + Written loop problems
  + `isLinear(v: number[]): boolean`
  + `rotateLeft(v: number[]): number[]`
  + `rotateRight(v: number[]): number[]`

#### Tuesday, 10/29

#### Thursday, 10/31
* Questions from the homework, J16 due tonight
  + `pig` game project

### Week Eleven
#### Monday, 11/4
* EXAM TWO

#### Tuesday, 11/5

#### Thursday, 11/7
* No assignment due

### Week Twelve
#### Monday, 11/11
* Questions from the homework, J17 due tonight
    + `rectangleWithBorder(rows: number, cols: number): string`
    + `htmlRectangleWithBorder(rows: number, cols: number): void`
    
#### Tuesday, 11/12

#### Thursday, 11/14
* Questions from the homework, J18 due tonight
    + `transpose(x: number[][]): number[][]`
    + `numLarger(x: number[][], y: number[][]): number`

### Week Thirteen
#### Monday, 11/18
    
#### Tuesday, 11/19

#### Thursday, 11/21

### Week Fourteen
#### Monday, 11/25
* Questions from the homework, J19 due tonight
    + Network client project
    
#### Tuesday, 11/26

#### Thursday, 11/28
* Thanksgiving Day, no class

### Week Fifteen
#### Monday, 12/2

#### Tuesday, 12/3

#### Thursday, 12/5
* Questions from the homework, J20 due tonight
    + Text mining project

### FINAL EXAM, Week of 12/9, Dates TBA
